### ISSUE TITLE
Plattform wechseln

### ISSUE THREAD

**Issue by gizzmo88** [VRLAB-HSKL/BuildSystem#12]
Als Entwickler möchte ich zwischen den Scenen und den dazugehörigen Plattformen wechseln können. So dass ich jederzeit in der Lage bin meine Anwendung auf unterschiedlichen Plattformen auszuführen.

**Comment by MBrill** [comment]
Lokal in Unity. Wir verwenden als Beispiel-ProjektTower of Hanoi.
Definition of Done: 
- Wir können zwischen Desktop, VIU und GVR hin- und herwechseln und für jede Plattform ein Build erstellen, das fehlerfrei gestartet auf der Plattform gestartet werden kann.
- Wir können HelloVR  ebenfalls zwischen den Plattformen Desktop, VIU und GVR wechseln und die Builds funktioniert auf den Plattformen.
